# Generated by Django 5.2.4 on 2025-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cooperative_id',
            field=models.CharField(blank=True, help_text='Required for cooperatives only!', max_length=50, null=True, unique=True),
        ),
    ]
