# Generated by Django 5.2.4 on 2025-08-05 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(help_text="Stores the document's unique identifier", primary_key=True, serialize=False)),
                ('type', models.TextField(help_text='Stores the document type, credit report, or loan agreement', max_length=50)),
                ('file_url', models.ImageField(help_text='Stores the URL of the file', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Stores the time the document was uploaded')),
                ('user', models.ForeignKey(help_text='Stores the user’s unique identifier', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
