# Generated by Django 5.2.4 on 2025-07-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerLoan', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score_at_application',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='current_outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
