# Generated by Django 5.2.4 on 2025-07-26 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerLoan', '0003_delete_loanapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'approved', 'disbursed', 'repaying'])), fields=('user', 'amount_requested', 'purpose', 'status'), name='unique_active_loan_per_user_amount_purpose'),
        ),
    ]
